<?php

namespace AppointmentsBundle\Repository;

/**
 * DetailStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailStatisticRepository extends \Doctrine\ORM\EntityRepository
{
}
