<?php

namespace AppointmentsBundle\Repository;

/**
 * statisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statisticRepository extends \Doctrine\ORM\EntityRepository
{
}
