services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
      UserBundle\Listener\LoginListener:
          arguments: ['@security.token_storage','@doctrine', '@session']
          tags:
              - { name: kernel.event_listener, event: security.interactive_login }
